LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := libvmacjni

# Also need the JNI headers.
LOCAL_C_INCLUDES += \
        $(JNI_H_INCLUDE)

LOCAL_SRC_FILES := GLOBGLUE.c IWMEMDEV.c KBRDEMDV.c M68KITAB.c MINEM68K.c MOUSEMDV.c ROMEMDEV.c RTCEMDEV.c SCCEMDEV.c SCRNEMDV.c SCSIEMDV.c SNDEMDEV.c SONYEMDV.c VIAEMDEV.c JNIGLUE.c

LOCAL_PRELINK_MODULE := false


include $(BUILD_SHARED_LIBRARY)
